// Unified Candidate AI Analysis (spec follow-up, schema.sql Section 46) — replaces the two separate
// comp-gemini-analysis (technical-only) and personality-gemini-analysis (personality-only) Edge
// Functions with ONE comprehensive, evidence-based analysis per candidate: personality profiling,
// behavioral pattern, technical/specialized evaluation, and job-fit, generated by a single Gemini
// call that reads both halves of the same comp_assessments row. The two old functions/tables are
// left in place untouched (historical data), this one is additive.
//
// Same JWT-forwarding pattern as both source functions: the Supabase client is built with the
// CALLING USER's own Authorization header, never a service-role key, so this only ever sees data
// that user's own RLS already grants.
//
// Unlike comp-gemini-analysis (which refuses outright when technical data isn't ready) this function
// degrades gracefully: the exam design lets a candidate go through either half independently, so it
// runs on whichever of technical/personality data is actually available and only refuses when
// NEITHER is.
//
// Schema types below are plain uppercase strings ("OBJECT"/"STRING"/...), matching Gemini's
// OpenAPI-subset wire schema exactly like the two source functions.

import { createClient } from 'npm:@supabase/supabase-js@2'
import { GoogleGenAI } from 'npm:@google/genai@1'

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' } })
}

function fail(status: number, message: string, err?: unknown) {
  console.error(`comp-candidate-ai-analysis: ${message}`, err ?? '')
  return json({ error: message }, status)
}

const COMPETENCY_DIMENSION_KEYS = ['technical', 'problem_solving', 'experience', 'hse', 'judgment', 'communication', 'leadership', 'commercial']

const COMPETENCY_DIMENSION_SCHEMA = {
  type: 'OBJECT',
  properties: {
    score: { type: 'NUMBER' },
    analysis: { type: 'STRING' },
    evidence: { type: 'ARRAY', items: { type: 'STRING' } },
  },
  required: ['score', 'analysis', 'evidence'],
}

const RESPONSE_SCHEMA = {
  type: 'OBJECT',
  properties: {
    executive_summary: { type: 'STRING' },
    technical_analysis: {
      type: 'OBJECT',
      properties: {
        available: { type: 'BOOLEAN' },
        competency_analysis: {
          type: 'OBJECT',
          properties: Object.fromEntries(COMPETENCY_DIMENSION_KEYS.map((key) => [key, COMPETENCY_DIMENSION_SCHEMA])),
          required: COMPETENCY_DIMENSION_KEYS,
        },
        strengths: { type: 'ARRAY', items: { type: 'STRING' } },
        development_areas: { type: 'ARRAY', items: { type: 'STRING' } },
        critical_gaps: { type: 'ARRAY', items: { type: 'STRING' } },
      },
      required: ['available', 'competency_analysis', 'strengths', 'development_areas', 'critical_gaps'],
    },
    personality_analysis: {
      type: 'OBJECT',
      properties: {
        available: { type: 'BOOLEAN' },
        response_validity_interpretation: { type: 'STRING' },
        trait_analysis: {
          type: 'ARRAY',
          items: {
            type: 'OBJECT',
            properties: {
              trait_key: { type: 'STRING' },
              score: { type: 'NUMBER' },
              range_label: { type: 'STRING' },
              analysis: { type: 'STRING' },
            },
            required: ['trait_key', 'score', 'range_label', 'analysis'],
          },
        },
        behavioral_analysis: {
          type: 'ARRAY',
          items: {
            type: 'OBJECT',
            properties: {
              dimension_key: { type: 'STRING' },
              score: { type: 'NUMBER' },
              analysis: { type: 'STRING' },
              evidence: { type: 'ARRAY', items: { type: 'STRING' } },
            },
            required: ['dimension_key', 'score', 'analysis', 'evidence'],
          },
        },
        observed_patterns: { type: 'ARRAY', items: { type: 'STRING' } },
        strength_patterns: { type: 'ARRAY', items: { type: 'STRING' } },
        watchpoints: { type: 'ARRAY', items: { type: 'STRING' } },
      },
      required: ['available', 'response_validity_interpretation', 'trait_analysis', 'behavioral_analysis', 'observed_patterns', 'strength_patterns', 'watchpoints'],
    },
    role_fit_narrative: { type: 'STRING' },
    development_areas: { type: 'ARRAY', items: { type: 'STRING' } },
    training_recommendations: { type: 'ARRAY', items: { type: 'STRING' } },
    career_development_paths: { type: 'ARRAY', items: { type: 'STRING' } },
    follow_up_questions: {
      type: 'ARRAY',
      items: {
        type: 'OBJECT',
        properties: {
          question: { type: 'STRING' },
          purpose: { type: 'STRING' },
          competency: { type: 'STRING' },
          dimension_key: { type: 'STRING' },
          evidence_to_look_for: { type: 'STRING' },
          positive_indicators: { type: 'ARRAY', items: { type: 'STRING' } },
          risk_indicators: { type: 'ARRAY', items: { type: 'STRING' } },
        },
        required: ['question', 'purpose', 'competency', 'dimension_key', 'evidence_to_look_for', 'positive_indicators', 'risk_indicators'],
      },
    },
    evidence: {
      type: 'ARRAY',
      items: {
        type: 'OBJECT',
        properties: {
          source_type: { type: 'STRING', enum: ['QUESTION', 'SJT', 'JUDGE_COMMENT', 'EXPERIENCE'] },
          source_id: { type: 'STRING' },
          dimension_key: { type: 'STRING' },
          note: { type: 'STRING' },
        },
        required: ['source_type', 'source_id', 'dimension_key', 'note'],
      },
    },
    confidence: { type: 'STRING', enum: ['low', 'medium', 'high'] },
  },
  required: [
    'executive_summary',
    'technical_analysis',
    'personality_analysis',
    'role_fit_narrative',
    'development_areas',
    'training_recommendations',
    'career_development_paths',
    'follow_up_questions',
    'evidence',
    'confidence',
  ],
}

const SYSTEM_INSTRUCTION = `تو یک دستیار تحلیل جامع ارزیابی متقاضیان (فنی/تخصصی + شخصیت و رفتار حرفه‌ای) برای استخدام در پروژه‌های EPC نفت و گاز هستی.
قوانین سخت‌گیرانه‌ای که باید رعایت کنی:
1. فقط از داده‌های واقعی ارائه‌شده (پاسخ‌های متقاضی، امتیازهای داوران، امتیازهای محاسبه‌شده ویژگی‌ها/ابعاد رفتاری، نتیجه اعتبارسنجی پاسخ) استفاده کن — هرگز اطلاعاتی که در داده‌ها نیست را اختراع نکن.
2. هرگز نتیجه‌گیری قطعی درباره استخدام، رد یا مناسب‌بودن نهایی متقاضی نده (مثل «قطعاً مناسب است»/«قطعاً مناسب نیست») — این ابزار صرفاً دستیار تحلیلی است، تصمیم نهایی همیشه با داوران/تیم استخدام و قوانین سیستم است.
3. هرگز شخصیت متقاضی را «برچسب‌گذاری تشخیصی» نکن (مثل نام بردن از اختلالات روانی) — فقط از زبان رفتاری-حرفه‌ای و مبتنی بر شواهد استفاده کن: «پاسخ‌های متقاضی نشان‌دهنده...»، «در حوزه X شواهد کافی مشاهده نشد...».
4. ورودی شامل دو بخش مستقل است: technical (ممکن است null باشد) و personality (ممکن است null باشد). اگر یکی از این دو null بود، بخش متناظر در خروجی را با available=false برگردان و در فیلدهای متنی آن صراحتاً بنویس «این بخش هنوز برای این متقاضی تکمیل نشده است» و آرایه‌ها را خالی و امتیازها را صفر بگذار — هرگز برای بخش موجود نیست چیزی حدس نزن.
5. اگر پاسخ متقاضی به یک سؤال فنی ناقص، متناقض، سطحی یا مبهم بود، یا یک بعد رفتاری امتیاز پایین/بحرانی داشت، یک سؤال پیگیری (follow_up_questions) دقیق برای مصاحبه ساختاریافته پیشنهاد بده که شواهد واقعی (نه فرضی) را بررسی کند.
6. هر تحلیل باید در صورت امکان به یک مدرک مشخص (evidence) با شناسه سؤال یا بعد مرتبط باشد.
7. اگر نتیجه اعتبارسنجی پاسخ‌های شخصیتی نشان‌دهنده پاسخ یکنواخت (straight-lining) یا پاسخ‌های ناقص بود، این موضوع را صریحاً در personality_analysis.response_validity_interpretation ذکر کن و تفسیر امتیازها را با احتیاط بیشتری بیان کن.
8. امتیاز هر بعد شایستگی فنی (competency_analysis) را بین ۰ تا ۱۰۰ بده و آن را صرفاً از روی امتیازهای واقعی ثبت‌شده داوران برای سؤالات مرتبط با همان بعد استخراج کن، نه حدس شخصی. اگر برای یک بعد هیچ سؤال یا امتیازی وجود نداشت، بنویس «شواهد کافی برای این حوزه ثبت نشده است» و امتیاز آن را صفر بگذار.
9. role_fit_narrative باید فقط زمانی یک تحلیل جامع و منسجم (۳ تا ۶ جمله) درباره تطابق متقاضی با ویژگی‌های رفتاری مورد نیاز شغل بنویسد که ورودی personality همراه با role_alignment موجود باشد — دقیقاً بر اساس اعداد داده‌شده در role_alignment (overall_alignment_percent و ردیف‌های rows) بنویس، هرگز عدد یا درصد جدیدی حدس نزن یا با آنچه داده شده مغایرت نداشته باش. اگر role_alignment.has_job_profile برابر false بود یا اصلاً personality/role_alignment در ورودی نبود، صراحتاً بنویس که تحلیل تطابق شغلی هنوز امکان‌پذیر نیست (نیم‌رخ رفتاری شغل تعریف نشده یا ارزیابی شخصیت هنوز کامل نشده). اگر critical_gap_count بزرگ‌تر از صفر بود، حتماً مشخص کن دقیقاً کدام بعد(های) حیاتی برآورده نشده‌اند و چرا این موضوع برای این شغل اهمیت دارد.
10. خلاصه اجرایی (executive_summary) باید کل تصویر موجود از متقاضی را در بر بگیرد — اگر فقط یکی از دو بخش فنی/شخصیتی موجود بود، صراحتاً به تکمیل‌نشدن بخش دیگر اشاره کن.
11. خروجی را کاملاً به فارسی و دقیقاً مطابق ساختار JSON درخواستی بنویس.`

function resolveOfficialScore(
  questionId: string,
  leadAnswers: Record<string, { score?: number | null; note?: string; candidateAnswer?: string }>,
  panelistScores: Array<{ submitted_at: string | null; answers: Record<string, { score?: number | null; note?: string }> }>,
): { score: number | null; notes: string[] } {
  const submitted = panelistScores.filter((p) => p.submitted_at)
  const notes: string[] = []
  if (submitted.length > 0) {
    const scores = submitted.map((p) => p.answers?.[questionId]?.score).filter((s): s is number => typeof s === 'number')
    for (const p of submitted) {
      const note = p.answers?.[questionId]?.note
      if (note) notes.push(note)
    }
    return { score: scores.length > 0 ? Math.round((scores.reduce((a, b) => a + b, 0) / scores.length) * 10) / 10 : null, notes }
  }
  const leadNote = leadAnswers?.[questionId]?.note
  if (leadNote) notes.push(leadNote)
  return { score: leadAnswers?.[questionId]?.score ?? null, notes }
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS_HEADERS })

  try {
    const geminiKey = Deno.env.get('GEMINI_API_KEY')
    if (!geminiKey) return fail(500, 'GEMINI_API_KEY تنظیم نشده است. لطفاً آن را در Supabase Edge Function Secrets تنظیم کنید.')

    const { assessmentId } = await req.json()
    if (!assessmentId) return fail(400, 'assessmentId الزامی است.')

    const authHeader = req.headers.get('Authorization')
    if (!authHeader) return fail(401, 'احراز هویت لازم است.')

    const supabase = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_ANON_KEY')!, {
      global: { headers: { Authorization: authHeader } },
    })

    const { data: assessment, error: assessmentError } = await supabase.from('comp_assessments').select('*').eq('id', assessmentId).single()
    if (assessmentError || !assessment) return fail(404, 'ارزیابی یافت نشد یا دسترسی مجاز نیست.', assessmentError)

    // Technical data is only available for a DB-backed (bank-driven) assessment — a candidate still
    // on the legacy fixed in-code PM rubric (selected_question_ids empty) isn't shaped like a bank
    // selection, exactly like comp-gemini-analysis's guard, but here that just means "no technical
    // half yet" rather than refusing the whole request.
    const selectedIds: string[] = Array.isArray(assessment.selected_question_ids) ? assessment.selected_question_ids : []
    const technicalRequested = selectedIds.length > 0

    const { data: personalityAssessment, error: personalityAssessmentError } = await supabase
      .from('personality_assessments')
      .select('*')
      .eq('assessment_id', assessmentId)
      .maybeSingle()
    if (personalityAssessmentError) return fail(500, `بارگذاری ارزیابی شخصیت ناموفق بود: ${personalityAssessmentError.message}`, personalityAssessmentError)

    const PERSONALITY_SCORED_STATUSES = ['FINGERPRINT', 'AI_ANALYSIS', 'FINAL_REVIEW', 'LOCKED', 'ARCHIVED']
    const personalityRequested = !!personalityAssessment && PERSONALITY_SCORED_STATUSES.includes(personalityAssessment.status)

    let technicalAvailable = false
    let technicalPayload: unknown = null

    if (technicalRequested) {
      const [{ data: panelistScores, error: panelistError }, { data: bankRows, error: bankError }] = await Promise.all([
        supabase.from('comp_panelist_scores').select('submitted_at, answers').eq('assessment_id', assessmentId),
        supabase.rpc('comp_question_bank_public'),
      ])
      if (panelistError) return fail(500, `بارگذاری امتیازهای داوران ناموفق بود: ${panelistError.message}`, panelistError)
      if (bankError) return fail(500, `بارگذاری بانک سؤالات ناموفق بود: ${bankError.message}`, bankError)

      const questions = (bankRows ?? []).filter((q: { id: string; job_role: string }) => selectedIds.includes(q.id))

      if (questions.length > 0) {
        const answersPayload = questions.map(
          (q: { id: string; category: string; sub_category: string; difficulty: string; question_text: string }) => {
            const { score, notes } = resolveOfficialScore(q.id, assessment.answers ?? {}, panelistScores ?? [])
            const candidateAnswer = (assessment.answers ?? {})[q.id]?.candidateAnswer ?? ''
            return {
              question_id: q.id,
              category: q.category,
              topic: q.sub_category,
              difficulty: q.difficulty,
              question_text: q.question_text,
              candidate_answer: candidateAnswer,
              judge_score_0_5: score,
              judge_notes: notes,
            }
          },
        )
        technicalAvailable = true
        technicalPayload = {
          assessment_structure: { total_questions: questions.length, question_types: [...new Set(questions.map((q: { category: string }) => q.category))] },
          questions_and_answers: answersPayload,
        }
      }
    }

    let personalityAvailable = false
    let personalityPayload: unknown = null
    let roleAlignmentPayload: unknown = null

    if (personalityRequested && personalityAssessment) {
      const personalityAssessmentId = personalityAssessment.id

      const [{ data: dimensionScores, error: scoresError }, { data: validity, error: validityError }, { data: responses, error: responsesError }] =
        await Promise.all([
          supabase
            .from('personality_dimension_scores')
            .select('score_kind, normalized_score, coverage_count, confidence, trait_id, dimension_id, personality_traits(key, label_fa), personality_behavioral_dimensions(key, label_fa)')
            .eq('personality_assessment_id', personalityAssessmentId),
          supabase.from('personality_validity_results').select('*').eq('personality_assessment_id', personalityAssessmentId).maybeSingle(),
          supabase
            .from('personality_responses')
            .select('question_id, response_value, personality_questions(question_text, question_type, options, trait_id, dimension_id)')
            .eq('personality_assessment_id', personalityAssessmentId),
        ])
      if (scoresError) return fail(500, `بارگذاری امتیازهای شخصیت ناموفق بود: ${scoresError.message}`, scoresError)
      if (validityError) return fail(500, `بارگذاری نتیجه اعتبارسنجی ناموفق بود: ${validityError.message}`, validityError)
      if (responsesError) return fail(500, `بارگذاری پاسخ‌های شخصیت ناموفق بود: ${responsesError.message}`, responsesError)

      if (dimensionScores && dimensionScores.length > 0) {
        let requirements: { dimension_id: string; weight: number; min_threshold: number | null; preferred_min: number | null; preferred_max: number | null; is_critical: boolean }[] = []
        if (personalityAssessment.job_profile_id) {
          const { data } = await supabase
            .from('personality_job_behavioral_requirements')
            .select('dimension_id, weight, min_threshold, preferred_min, preferred_max, is_critical')
            .eq('profile_id', personalityAssessment.job_profile_id)
          requirements = data ?? []
        }

        type ScoreRow = {
          score_kind: string
          normalized_score: number | null
          coverage_count: number
          confidence: string
          trait_id: string | null
          dimension_id: string | null
          personality_traits: { key: string; label_fa: string } | null
          personality_behavioral_dimensions: { key: string; label_fa: string } | null
        }

        const traitAnalysisInput = (dimensionScores as ScoreRow[])
          .filter((s) => s.score_kind === 'TRAIT')
          .map((s) => ({
            trait_key: s.personality_traits?.key ?? s.trait_id,
            trait_label_fa: s.personality_traits?.label_fa ?? null,
            normalized_score: s.normalized_score,
            coverage_count: s.coverage_count,
            confidence: s.confidence,
          }))

        const dimensionAnalysisInput = (dimensionScores as ScoreRow[])
          .filter((s) => s.score_kind === 'BEHAVIORAL_DIMENSION')
          .map((s) => {
            const req = requirements.find((r) => r.dimension_id === s.dimension_id)
            return {
              dimension_key: s.personality_behavioral_dimensions?.key ?? s.dimension_id,
              dimension_label_fa: s.personality_behavioral_dimensions?.label_fa ?? null,
              normalized_score: s.normalized_score,
              coverage_count: s.coverage_count,
              confidence: s.confidence,
              is_critical_for_role: req?.is_critical ?? false,
              min_threshold_for_role: req?.min_threshold ?? null,
            }
          })

        type ResponseRow = {
          question_id: string
          response_value: { selected?: number | string; selected_option?: string }
          personality_questions: {
            question_text: string
            question_type: string
            options: { key: string; label_fa: string; dimension_key?: string; score?: number }[] | null
            trait_id: string | null
            dimension_id: string | null
          } | null
        }

        const responseEvidence = ((responses as ResponseRow[] | null) ?? []).map((r) => {
          const q = r.personality_questions
          const chosenOption = q?.options?.find((o) => o.key === r.response_value?.selected_option)
          return {
            question_id: r.question_id,
            question_type: q?.question_type,
            question_text: q?.question_text,
            selected_value: r.response_value?.selected ?? null,
            chosen_option_label: chosenOption?.label_fa ?? null,
            chosen_option_dimension_key: chosenOption?.dimension_key ?? null,
          }
        })

        // Deterministic role-fit rows — intentionally the SAME computation as
        // src/modules/personality/lib/roleAlignment.ts and personality-gemini-analysis's own copy
        // of it (duplicated here rather than shared, since this Edge Function deploys as a single
        // standalone file with no access to the Vite app's src tree). Passed to Gemini so
        // role_fit_narrative below is always grounded in these exact numbers.
        function rowFitScore(score: number | null, minThreshold: number | null, preferredMin: number | null, preferredMax: number | null): number | null {
          if (score == null) return null
          if (minThreshold == null && preferredMin == null && preferredMax == null) return score
          if (minThreshold != null && score < minThreshold) return Math.max(0, (score / minThreshold) * 60)
          if (preferredMin != null && score < preferredMin) {
            const floor = minThreshold ?? 0
            const span = Math.max(1, preferredMin - floor)
            return 60 + Math.min(40, ((score - floor) / span) * 40)
          }
          if (preferredMax != null && score > preferredMax) return Math.max(50, 100 - (score - preferredMax))
          return 100
        }
        function rowStatus(score: number | null, minThreshold: number | null, preferredMin: number | null, preferredMax: number | null, isCritical: boolean) {
          if (score == null) return 'NO_DATA'
          if (minThreshold != null && score < minThreshold) return 'BELOW_MIN'
          if (preferredMin != null && score < preferredMin) return 'BELOW_PREFERRED'
          if (preferredMax != null && score > preferredMax) return 'ABOVE_PREFERRED'
          return isCritical ? 'MEETS_CRITICAL' : 'MEETS'
        }
        const roleAlignmentRows = requirements.map((req) => {
          const scoreRow = (dimensionScores as ScoreRow[]).find((s) => s.score_kind === 'BEHAVIORAL_DIMENSION' && s.dimension_id === req.dimension_id)
          const score = scoreRow?.normalized_score ?? null
          return {
            dimension_key: scoreRow?.personality_behavioral_dimensions?.key ?? req.dimension_id,
            dimension_label_fa: scoreRow?.personality_behavioral_dimensions?.label_fa ?? null,
            is_critical: req.is_critical,
            weight: req.weight,
            score,
            min_threshold: req.min_threshold,
            preferred_min: req.preferred_min,
            preferred_max: req.preferred_max,
            status: rowStatus(score, req.min_threshold, req.preferred_min, req.preferred_max, req.is_critical),
          }
        })
        const alignmentCovered = roleAlignmentRows.filter((r) => r.score != null)
        const alignmentWeightedSum = alignmentCovered.reduce((sum, r) => sum + (rowFitScore(r.score, r.min_threshold, r.preferred_min, r.preferred_max) ?? 0) * r.weight, 0)
        const alignmentTotalWeight = alignmentCovered.reduce((sum, r) => sum + r.weight, 0)
        const overallAlignmentPercent = alignmentTotalWeight > 0 ? Math.round(alignmentWeightedSum / alignmentTotalWeight) : null
        const criticalGapCount = roleAlignmentRows.filter((r) => r.is_critical && (r.status === 'BELOW_MIN' || r.status === 'BELOW_PREFERRED')).length

        personalityAvailable = true
        personalityPayload = {
          job_role: personalityAssessment.job_role,
          computed_patterns: personalityAssessment.computed_patterns,
          computed_watchpoints: personalityAssessment.computed_watchpoints,
          validity_result: validity
            ? {
                overall_status: validity.overall_status,
                straight_lining_flag: validity.straight_lining_flag,
                missing_response_count: validity.missing_response_count,
                completion_seconds: validity.completion_seconds,
              }
            : null,
          trait_scores: traitAnalysisInput,
          behavioral_dimension_scores: dimensionAnalysisInput,
          response_evidence: responseEvidence,
        }
        roleAlignmentPayload = {
          job_role: personalityAssessment.job_role,
          has_job_profile: requirements.length > 0,
          overall_alignment_percent: overallAlignmentPercent,
          critical_gap_count: criticalGapCount,
          rows: roleAlignmentRows,
        }
      }
    }

    if (!technicalAvailable && !personalityAvailable) {
      return fail(400, 'هنوز داده‌ای برای تحلیل جامع این متقاضی ثبت نشده است.')
    }

    const candidateProfile = {
      name: assessment.candidate_name,
      job_role: assessment.job_role,
      years_experience_total: assessment.years_experience_total,
      years_experience_pipeline: assessment.years_experience_pipeline,
      current_employer: assessment.current_employer,
      education: assessment.education,
      certifications: assessment.certifications,
      employment_history: assessment.employment_history,
      notable_projects: assessment.notable_projects,
    }

    const promptPayload = {
      candidate_profile: candidateProfile,
      technical: technicalAvailable ? technicalPayload : null,
      personality: personalityAvailable ? personalityPayload : null,
      role_alignment: personalityAvailable ? roleAlignmentPayload : null,
    }

    // gemini-2.5-flash was retired ("no longer available to new users") — Google's own 404 error
    // names gemini-3.6-flash as its replacement, same as comp-gemini-analysis/personality-gemini-analysis.
    const model = Deno.env.get('GEMINI_MODEL') || 'gemini-3.6-flash'
    let response
    try {
      const ai = new GoogleGenAI({ apiKey: geminiKey })
      response = await ai.models.generateContent({
        model,
        contents: `داده‌های زیر مربوط به یک ارزیابی جامع واقعی (فنی/تخصصی و شخصیت/رفتاری) است. طبق قوانین ارائه‌شده، آن را تحلیل کن:\n\n${JSON.stringify(promptPayload, null, 2)}`,
        config: {
          systemInstruction: SYSTEM_INSTRUCTION,
          responseMimeType: 'application/json',
          responseSchema: RESPONSE_SCHEMA,
        },
      })
    } catch (geminiErr) {
      const detail = geminiErr instanceof Error ? geminiErr.message : String(geminiErr)
      return fail(502, `فراخوانی Gemini ناموفق بود: ${detail}`, geminiErr)
    }

    const text = response.text
    if (!text) return fail(502, 'پاسخی از Gemini دریافت نشد.')

    let analysis: unknown
    try {
      analysis = JSON.parse(text)
    } catch (parseErr) {
      return fail(502, 'پاسخ Gemini قابل تجزیه به JSON نبود.', { parseErr, text })
    }

    const confidence = typeof (analysis as { confidence?: unknown }).confidence === 'string' ? (analysis as { confidence: string }).confidence : null

    const { data: inserted, error: insertError } = await supabase
      .from('comp_candidate_ai_analysis')
      .insert({ assessment_id: assessmentId, model, analysis, confidence })
      .select('*')
      .single()
    if (insertError) return fail(500, `ذخیره تحلیل ناموفق بود: ${insertError.message}`, insertError)

    await supabase.rpc('comp_log_audit', {
      p_action: 'CANDIDATE_AI_ANALYSIS_GENERATED',
      p_entity_type: 'comp_assessments',
      p_entity_id: assessmentId,
      p_previous: null,
      p_new: { model },
    })

    return json({ analysis: inserted })
  } catch (err) {
    return fail(500, err instanceof Error ? err.message : 'خطای غیرمنتظره', err)
  }
})
