-- Issue & Task management module (ported from 30-Day_Quick_Win_Challenge): tm_* tables, RLS, RPC and RBAC registration.
create table if not exists tm_projects (name text primary key, created_at timestamptz default now(), is_guide boolean not null default false, current_phase text not null default 'اجرا');
create table if not exists tm_cases (id bigint generated by default as identity primary key, project_name text not null, organization text, status text not null default 'پیشنهاد', proposed_at timestamptz default now(), created_by text, title text not null, plan_responsible text, plan_target_date date, impact_delay_days numeric, impact_cost_avoided numeric, execution_target_date date, actual_result text, actual_value_json jsonb, closed_at timestamptz, created_at timestamptz not null default now());
create table if not exists tm_case_updates (id bigint generated by default as identity primary key, case_id bigint, kind text not null, created_at timestamptz not null default now(), created_by text, status text, progress_percent numeric, note text, reported_by text, title text, responsible_name text, responsible_email text, due_date date, task_status text, completed_at timestamptz, overdue_notified_at timestamptz, submitted_at timestamptz, submitted_note text, start_date date, severity text, responsible_unit text, project_name text, description text);
create table if not exists tm_project_issues (id bigint generated by default as identity primary key, project_name text not null, title text not null, description text, responsible_name text not null, responsible_email text not null, severity text not null default 'متوسط', status text not null default 'باز', due_date date not null, created_by text not null, created_at timestamptz not null default now(), updated_at timestamptz, submitted_at timestamptz, submitted_note text, completed_at timestamptz);
create table if not exists tm_users (user_id uuid primary key, email text not null, role text not null default 'manager', first_name text, last_name text, organization text);
create table if not exists tm_project_users (id bigint generated by default as identity primary key, user_id uuid not null, project_name text not null, organization text not null default '');

alter table tm_projects enable row level security; create policy tm_projects_all on tm_projects for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table tm_cases enable row level security; create policy tm_cases_all on tm_cases for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table tm_case_updates enable row level security; create policy tm_case_updates_all on tm_case_updates for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table tm_project_issues enable row level security; create policy tm_project_issues_all on tm_project_issues for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table tm_users enable row level security; create policy tm_users_all on tm_users for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table tm_project_users enable row level security; create policy tm_project_users_all on tm_project_users for all using (auth.uid() is not null) with check (auth.uid() is not null);

create or replace function tm_list_project_users(p_project_name text) returns table (user_id uuid, email text, first_name text, last_name text, organization text) language sql stable security definer set search_path = public as $$
  select u.user_id, u.email, u.first_name, u.last_name, pu.organization from tm_project_users pu join tm_users u on u.user_id = pu.user_id where pu.project_name = p_project_name
  union select u.user_id, u.email, u.first_name, u.last_name, 'ادمین سامانه' from tm_users u where u.role = 'admin'
  order by 3 nulls last, 4 nulls last, 2 $$;
grant execute on function tm_list_project_users(text) to authenticated;

insert into rasta_modules (key, label_fa) values ('taskissue', 'مدیریت موانع و اقدامات') on conflict (key) do nothing;
insert into rasta_permissions (module_key, action) select 'taskissue', a.action from (values ('view'),('create'),('edit'),('delete'),('submit'),('review'),('approve'),('reject'),('export'),('configure')) as a(action) on conflict (module_key, action) do nothing;
insert into rasta_role_permissions (role_id, permission_id) select r.id, p.id from rasta_roles r cross join rasta_permissions p where r.name = 'دسترسی کامل' and p.module_key = 'taskissue' on conflict do nothing;
