-- RLS: any signed-in user (same convention as the plc_* tables).
alter table sg_lifecycle_phases enable row level security;
drop policy if exists "sg_lifecycle_phases_all" on sg_lifecycle_phases;
create policy "sg_lifecycle_phases_all" on sg_lifecycle_phases for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_objectives enable row level security;
drop policy if exists "sg_lifecycle_objectives_all" on sg_lifecycle_objectives;
create policy "sg_lifecycle_objectives_all" on sg_lifecycle_objectives for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_outputs enable row level security;
drop policy if exists "sg_lifecycle_outputs_all" on sg_lifecycle_outputs;
create policy "sg_lifecycle_outputs_all" on sg_lifecycle_outputs for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_criteria enable row level security;
drop policy if exists "sg_lifecycle_criteria_all" on sg_lifecycle_criteria;
create policy "sg_lifecycle_criteria_all" on sg_lifecycle_criteria for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_phase_durations enable row level security;
drop policy if exists "sg_lifecycle_phase_durations_all" on sg_lifecycle_phase_durations;
create policy "sg_lifecycle_phase_durations_all" on sg_lifecycle_phase_durations for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_strategy_phase_dependencies enable row level security;
drop policy if exists "sg_lifecycle_strategy_phase_dependencies_all" on sg_lifecycle_strategy_phase_dependencies;
create policy "sg_lifecycle_strategy_phase_dependencies_all" on sg_lifecycle_strategy_phase_dependencies for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_master_schedule_versions enable row level security;
drop policy if exists "sg_lifecycle_master_schedule_versions_all" on sg_lifecycle_master_schedule_versions;
create policy "sg_lifecycle_master_schedule_versions_all" on sg_lifecycle_master_schedule_versions for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_master_schedule enable row level security;
drop policy if exists "sg_lifecycle_master_schedule_all" on sg_lifecycle_master_schedule;
create policy "sg_lifecycle_master_schedule_all" on sg_lifecycle_master_schedule for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_schedule_items enable row level security;
drop policy if exists "sg_lifecycle_schedule_items_all" on sg_lifecycle_schedule_items;
create policy "sg_lifecycle_schedule_items_all" on sg_lifecycle_schedule_items for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_schedule_dependencies enable row level security;
drop policy if exists "sg_lifecycle_schedule_dependencies_all" on sg_lifecycle_schedule_dependencies;
create policy "sg_lifecycle_schedule_dependencies_all" on sg_lifecycle_schedule_dependencies for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_schedule_baselines enable row level security;
drop policy if exists "sg_lifecycle_schedule_baselines_all" on sg_lifecycle_schedule_baselines;
create policy "sg_lifecycle_schedule_baselines_all" on sg_lifecycle_schedule_baselines for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_schedule_baseline_items enable row level security;
drop policy if exists "sg_lifecycle_schedule_baseline_items_all" on sg_lifecycle_schedule_baseline_items;
create policy "sg_lifecycle_schedule_baseline_items_all" on sg_lifecycle_schedule_baseline_items for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_schedule_success_templates enable row level security;
drop policy if exists "sg_lifecycle_schedule_success_templates_all" on sg_lifecycle_schedule_success_templates;
create policy "sg_lifecycle_schedule_success_templates_all" on sg_lifecycle_schedule_success_templates for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_schedule_success_template_items enable row level security;
drop policy if exists "sg_lifecycle_schedule_success_template_items_all" on sg_lifecycle_schedule_success_template_items;
create policy "sg_lifecycle_schedule_success_template_items_all" on sg_lifecycle_schedule_success_template_items for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_schedule_success_template_phases enable row level security;
drop policy if exists "sg_lifecycle_schedule_success_template_phases_all" on sg_lifecycle_schedule_success_template_phases;
create policy "sg_lifecycle_schedule_success_template_phases_all" on sg_lifecycle_schedule_success_template_phases for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_project_lifecycle_phases enable row level security;
drop policy if exists "sg_project_lifecycle_phases_all" on sg_project_lifecycle_phases;
create policy "sg_project_lifecycle_phases_all" on sg_project_lifecycle_phases for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_project_phase_items enable row level security;
drop policy if exists "sg_project_phase_items_all" on sg_project_phase_items;
create policy "sg_project_phase_items_all" on sg_project_phase_items for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_gate_decisions enable row level security;
drop policy if exists "sg_lifecycle_gate_decisions_all" on sg_lifecycle_gate_decisions;
create policy "sg_lifecycle_gate_decisions_all" on sg_lifecycle_gate_decisions for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_progress_history enable row level security;
drop policy if exists "sg_lifecycle_progress_history_all" on sg_lifecycle_progress_history;
create policy "sg_lifecycle_progress_history_all" on sg_lifecycle_progress_history for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_lifecycle_audit_log enable row level security;
drop policy if exists "sg_lifecycle_audit_log_all" on sg_lifecycle_audit_log;
create policy "sg_lifecycle_audit_log_all" on sg_lifecycle_audit_log for all using (auth.uid() is not null) with check (auth.uid() is not null);
alter table sg_projects enable row level security;
drop policy if exists "sg_projects_all" on sg_projects;
create policy "sg_projects_all" on sg_projects for all using (auth.uid() is not null) with check (auth.uid() is not null);
